### ISSUE TITLE
Celsius issue 

### ISSUE THREAD

**Issue by kiks46** [jslawinsk/BrewTempController#1]
Hi,
When I change the temperature to celsius it doesn't measure it, on the main screen says -17, and it is impossible to change target temp.

Thanks

**Comment by jslawinsk** [comment]
Interesting, I'll review the code,

**Comment by jslawinsk** [comment]
Just updated the code to address the Celsius issue. The code was updated to use a formula instead of the DallasTemperature::toCelsius method. The rotary encoder also updated to detect the correct direction between Wemos d1 and Arduino Uno.

Thank you for spotting the issue, please try the latest version.

**Comment by kiks46** [comment]
Cheers man, your project is awesome! I'm soldering the board to fit it all in a box... once it's done I will update it and I will let you know...
Thanks!
